# Generated by Django 3.0.10 on 2020-11-25 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0002_auto_20201120_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='stripecustomer',
            name='product',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stripecustomer',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('trial', 'Trial'), ('cancelled', 'Cancelled'), ('unpaid', 'Unpaid'), ('incomplete', 'Incomplete')], default='trial', max_length=10),
        ),
        migrations.AddField(
            model_name='stripecustomer',
            name='subscription_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stripecustomer',
            name='subscription_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
