# Generated by Django 3.0.10 on 2020-11-27 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0003_auto_20201125_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='stripecustomer',
            name='product_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
