# Generated by Django 3.0.10 on 2020-11-29 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0005_auto_20201129_0936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stripecustomer',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('trialing', 'Trial'), ('cancelled', 'Cancelled'), ('unpaid', 'Unpaid'), ('incomplete', 'Incomplete')], default='trialing', max_length=10),
        ),
    ]
