# Generated by Django 3.0.10 on 2020-11-29 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0006_auto_20201129_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='stripecustomer',
            name='subscription_cache',
            field=models.TextField(blank=True, null=True),
        ),
    ]
