# Generated by Django 3.0.10 on 2020-12-05 23:13

from django.db import migrations, models
import journal_app.subscription.models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0007_stripecustomer_subscription_cache'),
    ]

    operations = [
        migrations.AddField(
            model_name='stripecustomer',
            name='trial_end',
            field=models.DateTimeField(default=journal_app.subscription.models.trial_end_date),
        ),
        migrations.AlterField(
            model_name='stripecustomer',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='stripecustomer',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
