# Generated by Django 3.0.10 on 2021-03-17 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0008_auto_20201205_1713'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_key', models.CharField(max_length=30)),
            ],
        ),
    ]
