# Generated by Django 3.0.10 on 2021-08-17 01:52

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0009_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_price_id', models.CharField(max_length=30)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('name', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('bullet_point_1', models.CharField(max_length=75)),
                ('bullet_point_2', models.CharField(max_length=75)),
                ('bullet_point_3', models.CharField(max_length=75)),
                ('bullet_point_4', models.CharField(max_length=75)),
            ],
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
