# Generated by Django 3.0.10 on 2021-08-17 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0011_subscription_price_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='bullet_point_1',
            field=models.CharField(blank=True, max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='bullet_point_2',
            field=models.CharField(blank=True, max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='bullet_point_3',
            field=models.CharField(blank=True, max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='bullet_point_4',
            field=models.CharField(blank=True, max_length=75, null=True),
        ),
    ]
