# Generated by Django 3.0.10 on 2021-08-22 17:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subscription', '0012_auto_20210816_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='stripecustomer',
            name='subscription',
            field=models.ManyToManyField(blank=True, null=True, to='subscription.Subscription'),
        ),
        migrations.AlterField(
            model_name='stripecustomer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to=settings.AUTH_USER_MODEL),
        ),
    ]
