# Generated by Django 3.0.10 on 2021-08-22 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0013_auto_20210822_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stripecustomer',
            name='subscription',
            field=models.ManyToManyField(blank=True, to='subscription.Subscription'),
        ),
    ]
