# Generated by Django 3.0.10 on 2021-08-22 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0014_auto_20210822_1256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stripecustomer',
            name='subscription',
        ),
        migrations.AddField(
            model_name='stripecustomer',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='subscription.Subscription'),
        ),
    ]
