# Generated by Django 3.0.10 on 2021-01-20 02:36

import django.db.models.deletion
from django.db import migrations, models

import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0005_auto_20210119_2036'),
        ('journal_mail', '0003_auto_20201207_0802'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('to', phone_field.models.PhoneField(blank=True, max_length=31, null=True)),
                ('sent_on', models.DateTimeField(blank=True)),
                ('contact', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='journal.Contact')),
            ],
        ),
    ]
