# Generated by Django 3.0.10 on 2021-01-20 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal_mail', '0004_textmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='textmessage',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='textmessage',
            name='sid',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='textmessage',
            name='status',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='textmessage',
            name='to',
            field=models.TextField(blank=True, null=True),
        ),
    ]
