# Generated by Django 3.0.10 on 2021-01-24 21:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal_mail', '0006_auto_20210119_2117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='textmessage',
            name='to',
        ),
        migrations.AddField(
            model_name='textmessage',
            name='number',
            field=models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must be 10 digits long with no spaces, dashes, or parenthesis', regex='^\\d{10}$')]),
        ),
    ]
