# Generated by Django 3.0.10 on 2021-02-02 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal_mail', '0007_auto_20210124_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textmessage',
            name='sent_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
