# Generated by Django 3.0.10 on 2021-02-02 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal_mail', '0008_auto_20210201_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textmessage',
            name='sent_on',
            field=models.DateTimeField(blank=True),
        ),
    ]
