# Generated by Django 3.0.10 on 2021-07-23 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal_mail', '0011_auto_20210630_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mail',
            name='email_from',
            field=models.EmailField(default='No Reply <noreply@cjstein.com>', max_length=254),
        ),
    ]
