# Generated by Django 3.0.10 on 2020-11-02 03:35

from django.conf import settings
from django.db import migrations, models
import mail.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, max_length=100, null=True)),
                ('header', models.CharField(max_length=50)),
                ('to', models.EmailField(max_length=254)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('email_from', models.EmailField(default='No Reply <noreply@cjstein.com>', max_length=254)),
                ('html_message', models.TextField()),
                ('template_name', models.CharField(max_length=40)),
                ('user', models.ForeignKey(on_delete=models.SET(mail.models.get_sentinel_user), to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
