# Generated by Django 3.0.10 on 2020-10-15 19:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20201014_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='days_to_release',
            field=models.IntegerField(default=7),
        ),
        migrations.AddField(
            model_name='user',
            name='last_checkin',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 15, 19, 18, 5, 76696, tzinfo=utc)),
        ),
    ]
