# Generated by Django 3.0.10 on 2020-12-05 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20201205_1336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_trial',
        ),
        migrations.RemoveField(
            model_name='user',
            name='trial_end',
        ),
    ]
