# Generated by Django 3.0.10 on 2020-10-15 19:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20201015_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='checkin_link',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_checkin',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 15, 19, 21, 46, 305758, tzinfo=utc)),
        ),
    ]
