# Generated by Django 3.0.10 on 2020-10-19 13:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20201015_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_checkin',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
