# Generated by Django 3.0.10 on 2020-11-03 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20201019_0815'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='days_to_release',
            new_name='days_to_release_setting',
        ),
        migrations.AddField(
            model_name='user',
            name='entries_released',
            field=models.BooleanField(default=False),
        ),
    ]
