# Generated by Django 3.0.10 on 2020-10-09 02:26

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_auto_20201006_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='body',
            field=tinymce.models.HTMLField(),
        ),
    ]
