# Generated by Django 3.0.10 on 2021-01-14 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0003_auto_20201117_1943'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='is_scheduled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='entry',
            name='scheduled_time',
            field=models.DateField(blank=True, null=True),
        ),
    ]
