# Generated by Django 3.0.10 on 2021-01-20 02:36

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0004_auto_20210113_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=phone_field.models.PhoneField(blank=True, max_length=31, null=True),
        ),
    ]
