# Generated by Django 3.0.10 on 2020-10-15 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0004_auto_20201011_1208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='password',
        ),
    ]
