# Generated by Django 3.0.10 on 2020-10-20 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0005_remove_contact_password'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['name']},
        ),
    ]
