# Generated by Django 3.0.10 on 2021-01-20 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0005_auto_20210119_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='phone_formatted',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.TextField(blank=True, null=True),
        ),
    ]
