# Generated by Django 3.0.10 on 2021-01-20 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0006_auto_20210119_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone_formatted',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
